spring:
  application:
    name: store
  
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres  
    password: root
    driver-class-name: org.postgresql.Driver

stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  
  supported-currencies: USD,EUR,UAH 

payment-gateway: stripe

mail:
  host: smtp.gmail.com
  port: 587