spring:
  application:
   name: store

stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currentices: USD,EUR,UAH

payment-gateway: stripe
mail:
  host: https://smtp.gmail.com
  port: 5761